ALTER TABLE public.bot_settings
  ADD COLUMN IF NOT EXISTS auto_run BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS run_until TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS last_tick_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS day_loss NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS day_loss_date DATE NOT NULL DEFAULT CURRENT_DATE;